export default {
  login: "Layouwen",
  id: 60692794,
  node_id: "MDQ6VXNlcjYwNjkyNzk0",
  avatar_url: "https://avatars.githubusercontent.com/u/60692794?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Layouwen",
  html_url: "https://github.com/Layouwen",
  followers_url: "https://api.github.com/users/Layouwen/followers",
  following_url: "https://api.github.com/users/Layouwen/following{/other_user}",
  gists_url: "https://api.github.com/users/Layouwen/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Layouwen/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Layouwen/subscriptions",
  organizations_url: "https://api.github.com/users/Layouwen/orgs",
  repos_url: "https://api.github.com/users/Layouwen/repos",
  events_url: "https://api.github.com/users/Layouwen/events{/privacy}",
  received_events_url: "https://api.github.com/users/Layouwen/received_events",
  type: "User",
  site_admin: false,
  name: "Avan",
  company: null,
  blog: "easyhappy.top",
  location: "GuangZhou China",
  email: "layouwen@gmail.com",
  hireable: null,
  bio: "Keep Learning...",
  twitter_username: null,
  public_repos: 64,
  public_gists: 0,
  followers: 10,
  following: 36,
  created_at: "2020-02-05T10:00:40Z",
  updated_at: "2023-04-02T07:11:18Z",
  private_gists: 0,
  total_private_repos: 4,
  owned_private_repos: 4,
  disk_usage: 66956,
  collaborators: 0,
  two_factor_authentication: false,
  plan: {
    name: "free",
    space: 976562499,
    collaborators: 0,
    private_repos: 10000,
  },
};
